### ISSUE TITLE
#2 Add the ability for companies to log in

### ISSUE THREAD

**Issue by WebDevSimplified** [WebDevSimplified/React-Simplified-Bonus-Project#2]
# Feature Description

In order to implement a job board we need a way for individual users from a company to create an account. This feature has nothing to do with actually implementing job listings, but is a preliminary task for adding user authentication.

## Tasks

- [ ] Add log in/sign up pages
- [ ] Persist user log in status by checking for the current user's session when they first load the application
- [ ] Add a modal that pops up while waiting for user log out to finish

### Not Logged In View
![Not Logged In View](https://github.com/WebDevSimplified/React-Simplified-Bonus-Project/assets/39717099/a4a1fdb0-d7b8-4430-88d9-79671882da7e)

### Logged In View
![Logged In View](https://github.com/WebDevSimplified/React-Simplified-Bonus-Project/assets/39717099/607a9e69-5fa7-475c-82d4-a9dce73e0079)

### Not Logged In Mobile View
![Not Logged In Mobile View](https://github.com/WebDevSimplified/React-Simplified-Bonus-Project/assets/39717099/34c623c6-5257-455b-b0b4-1ca520d3259f)

### Logged In Mobile View
![Logged In Mobile View](https://github.com/WebDevSimplified/React-Simplified-Bonus-Project/assets/39717099/0e32d122-d69d-4c5c-b923-4305f1274d3f)

### Log In Page
![Log In Page](https://github.com/WebDevSimplified/React-Simplified-Bonus-Project/assets/39717099/c2fdeed3-4568-4be2-b510-4b934b3ba84b)

### Sign Up Page
![Sign Up Page](https://github.com/WebDevSimplified/React-Simplified-Bonus-Project/assets/39717099/631118a1-43a3-4257-8c69-2cebcfffbd64)

### Logging Out Modal
![Logging Out Modal](https://github.com/WebDevSimplified/React-Simplified-Bonus-Project/assets/39717099/dace8850-99d1-4e65-8600-96ffdf1ce3cf)

**Comment by WebDevSimplified** [comment]
**Team Lead:**

Don't forget to validate the user input in the forms before sending it off to the API. Also, make sure you show the errors messages to the user if there are any. You can look at the [TaskForm](https://github.com/WebDevSimplified/React-Simplified-Bonus-Project/blob/main/job-board/before/client/src/features/task-list/components/TaskForm.tsx) component for an example of how this can be done.

Also, the designs for this section include links to many pages that do not exist yet. Just ignore those links for now.

**Comment by WebDevSimplified** [comment]
**Backend Lead:**

Remember that we use cookies on the backend for user session tracking. This means you will need to send up the cookie with each request that you want to be authenticated and you will also need to hit the API to get the user's information the first time the page loads in case they are logged in and already have a session cookie stored on their device.

**Comment by BlackBond06** [comment]
Hi WebDevSimplified, I'm a big fan of your work. 

I really want to start contributing to open source projects and I feel this issue would be a nice challenge for me.
So if this issue is still open, I would really love to contribute to this wonderful project by resolving it.

Looking forward to your response.
Thank you.
