### ISSUE TITLE
#3 Add the ability for authenticated users to create, edit, and delete job listings

### ISSUE THREAD

**Issue by WebDevSimplified** [WebDevSimplified/React-Simplified-Bonus-Project#3]
# Feature Description

Once user authentication is implemented we can focus on the main priority for this round of features which is job listings. In this first feature we just need the ability for users to create, edit, and delete job listings. We will focus on payments and publishing job listings in another feature. Only authenticated users should be able to create job listings so these pages should only be accessible if the user is logged in.

## Tasks

- [ ] Add My Listings page
- [ ] Add New/Edit Listing forms
- [ ] Add a preview of the job listing on the new/edit forms
- [ ] Add the ability to delete listings

### My Job Listings Page
![My Job Listings Page](https://github.com/WebDevSimplified/React-Simplified-Bonus-Project/assets/39717099/e6b92f77-82e8-45b7-9a4d-eb396862a704)

### New Listing Page
![New Listing Page](https://github.com/WebDevSimplified/React-Simplified-Bonus-Project/assets/39717099/1e1de42e-15fa-4351-a38d-c9fb2f38015c)

### Edit Listing Page
![Edit Listing Page](https://github.com/WebDevSimplified/React-Simplified-Bonus-Project/assets/39717099/c89d4304-1613-47f7-9e96-8eed63408dcd)

### Preview Visible
![Preview Visible](https://github.com/WebDevSimplified/React-Simplified-Bonus-Project/assets/39717099/526796fd-4edb-45ef-921f-0d799ca6189d)

### View More Preview Modal
![View More Preview Modal](https://github.com/WebDevSimplified/React-Simplified-Bonus-Project/assets/39717099/5b13dc76-1512-4816-98c6-e45227772cd7)

### Delete Listing Confirmation Modal
![Delete Listing Confirmation Modal](https://github.com/WebDevSimplified/React-Simplified-Bonus-Project/assets/39717099/474b34b9-6051-4ed9-8f59-e46ee9a63256)

**Comment by WebDevSimplified** [comment]
**Team Lead:**

Don't forget about form validation errors. Also, keep in mind what the loading state will look like for users on slower connections.

Lastly, you will notice that these mockups have buttons for extending/publishing job listings. This is not something we are tackling in this task so you can ignore those buttons for now.
