### ISSUE TITLE
#4 Add the ability for users to publish job listings

### ISSUE THREAD

**Issue by WebDevSimplified** [WebDevSimplified/React-Simplified-Bonus-Project#4]
# Feature Description

This feature is fairly simple in that it only focuses on adding the ability for users to pay to publish their job listings and/or extend their current job listings. This does not cover the page for other people to view public job listings.

## Tasks

- [ ] Add the ability for users to pay to extend/publish job listings
- [ ] Add an order confirmation page to direct users to after a successful payment
- [ ] Add proper badges that display the status and time remaining on the my job listings page

### Badge Examples
![Badge Examples](https://github.com/WebDevSimplified/React-Simplified-Bonus-Project/assets/39717099/42eb0e69-4741-4739-8b87-cdbfb449bf7a)

### Publish/Extend Dropdown
![Publish/Extend Dropdown](https://github.com/WebDevSimplified/React-Simplified-Bonus-Project/assets/39717099/4d388510-2048-48fe-91c6-7b21065195a4)

### Payment Modal
![Payment Modal](https://github.com/WebDevSimplified/React-Simplified-Bonus-Project/assets/39717099/35f2a77f-bc30-4acb-91b6-71437c6ef899)

### Order Complete Page
![Order Complete Page](https://github.com/WebDevSimplified/React-Simplified-Bonus-Project/assets/39717099/89841cc1-d20c-4e62-9c0f-09553c43efa9)

**Comment by WebDevSimplified** [comment]
**Backend Lead:**

Don't forget to review my notes on how to setup/test our Stripe integration on the backend.
