### ISSUE TITLE
#5 Public Job Listing Page

### ISSUE THREAD

**Issue by WebDevSimplified** [WebDevSimplified/React-Simplified-Bonus-Project#5]
# Feature Description

This feature is the final job listing feature and is all about giving the public the ability to view published job listings. This feature should include a page for viewing all public job listings, the ability to filter job listings, and the ability to hide/favorite job listings. Hiding/favoriting job listings should be persisted for the user so if they come back on the same device they will keep their favorite/hidden jobs.

## Tasks

- [ ] Add a publicly accessible job listing page for viewing published listings
- [ ] Add filters to the job listing page
- [ ] Add hide/favorite buttons to each job listing
- [ ] When a job is hidden a toast message should pop up that lets the user undo the favoriting of a job

### Job Listing Page
![Job Listing Page](https://github.com/WebDevSimplified/React-Simplified-Bonus-Project/assets/39717099/22fd5424-f4a7-4b4f-b8d3-7684fc7cbdb4)

### Job Hidden Toast Message
![Job Hidden Toast Message](https://github.com/WebDevSimplified/React-Simplified-Bonus-Project/assets/39717099/51675419-b4c9-4ed5-998d-cf98b55fc6d9)

**Comment by WebDevSimplified** [comment]
**Team Lead:**

Remember to include loading animations.
